apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopherlabs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopherlabs
  template:
    metadata:
      labels:
        app: gopherlabs
    spec:
      containers:
      - image: sangam/gopherlabs
        name: gopherlabs

---

apiVersion: v1
kind: Service
metadata:
  name: gopherlabs
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hello-world"
    port: 3999:8080
  selector:
    app: gopherlabs